SET IDENTITY_INSERT [dbo].[Staff] ON
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (1, N'Beng Han                      ', N'imbenghan@gmail.com           ', N'beng123             ', N'0173669089          ', N'Staff     ', 10000, NULL, NULL)
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (2, N'Cheong Loong                  ', N'cl@gmail.com                  ', N'cl123               ', N'0123456789          ', N'Trainer   ', 1000, 2000, N'Fitness')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (3, N'Weng Fai                      ', N'wengfai@gmail.com             ', N'wf123               ', N'0123345678          ', N'Trainer   ', 2000, 1000, N'Dance')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (4, N'Ezra                          ', N'ezra@gmail.com                ', N'ezra123             ', N'0123445678          ', N'Trainer   ', 0, 3000, N'Yoga')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (5, N'Bryan Lee', N'bryan@gmail.com', N'bryan123', N'0123455678', N'Trainer', 500, 1500, N'ALL')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (6, N'Bruce Lee', N'bruce@gmail.com', N'bruce123', N'0123456678', N'Trainer', 2000, 8000, N'Fitness')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (7, N'The Rock', N'rock@gmail.com', N'rock123', N'0178945612', N'Trainer', 1000, 5000, N'ALL')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (8, N'Triple H', N'tripleH@gmail.com', N'triple123', N'0144404440', N'Trainer', 500, 2000, N'Fitness')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (9, N'Yoga Master', N'yoga@gmail.com', N'yoga123', N'0179876543', N'Trainer', 0, 4000, N'Yoga')
INSERT INTO [dbo].[Staff] ([sId], [sName], [sEmail], [sPassword], [sPhoneNo], [sType], [basicSalary], [tFees], [tType]) VALUES (10, N'Dancing King', N'dk@gmail.com', N'dk123', N'0169876542', N'Trainer', 0, 4000, N'Dance')
SET IDENTITY_INSERT [dbo].[Staff] OFF
